# This is a basic workflow to help you get started with Actions

name: Newman Test Run CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman
        run: npm install -g newman

      - name: Running first collection
        run: newman run AutomationExercise_API_Testing.postman_collection.json --suppress-exit-code

      - name: Running second collection with environment
        run: newman run DevEnvironment.postman_collection.json -e DevEnvironment.postman_environment.json --suppress-exit-code
